### PR TITLE
Improve documentation

### LINKED ISSUE #28: Document existing endpoints
Existing endpoints lack documentation. Proper documentation should be included in the README, and if possible, TSDoc, to help with the development workflow.

### PR DESCRIPTION
**Pull request by AtilioA**
Adds `typedoc` to generate documentation from comments following TSDoc or something.
I'll keep adding more comments to this PR before marking it as ready.
Resolves #28.

### CODE REVIEW

**Comment by AtilioA** [comment]
https://github.com/AtilioA/AlertaDoTesouro/pull/35/files#diff-f3eab147f9c67d8aeb9f4f641a6b199d8b9eebae738083ea2f9a4a79aaca0175 will screw us :cowboy_hat_face:

**Comment by AtilioA** [comment]
:notes:

**Comment by AtilioA** [comment]
why did I do this

**Comment by AtilioA** [comment]
code is not even compiling I don't even know how this looks like


(it is doe)

**Comment by AtilioA** [comment]
on top of that I did this while watching Gregório Duvivier x Ciro Gomes

**Review by Henriquelay — CHANGES_REQUESTED** [review]
I can't get it to run with this minimal `tsconfig.json`. I am working on it

**Comment by AtilioA** [comment]
Should work now, I'm running `typedoc` with `npx typedoc --out docs`.

**Comment by Henriquelay** [comment]
I tried it out and `yarn typedoc` works fine.
I can't understand a thing about this doc tool UI! But that's a me problem 🤠

**Comment by Henriquelay** [comment]
LGTM 👍

**Review by Henriquelay — APPROVED** [review]

**Pull request merged**
